### ISSUE TITLE
User-agent and sid

### ISSUE THREAD

**Issue by kerphi** [Inist-CNRS/node-ezs-istex#1]
Pour des besoins de statistiques, serait il possible de régler le user agent des requêtes http à node-ezs-istex et de rajouter dans toutes les Url appelées sur l'API de paramètre sid=node-ezs-istex

Cela permettra alors de mieux identifier l'usage côté ezmesure.

**Comment by parmentf** [comment]
Beaucoup des instructions de ezs-istex comprennent un sid.
Je ferme cette issue.
La suite se passe sur [Inist-CNRS/ezs](https://github.com/Inist-CNRS/ezs)
